// Code generated by goctl. DO NOT EDIT.
package types

type Response struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type SetTitleRequest struct {
	Title  string `json:"title"`
	Size   int    `json:"size"`
	Family string `json:"family"`
	Color  string `json:"color"`
}

type GetTitleResponse struct {
	Title  string `json:"title"`
	Size   int    `json:"size"`
	Family string `json:"family"`
	Color  string `json:"color"`
}

type NullRequest struct {
}
