// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	resourceFieldNames          = builder.RawFieldNames(&Resource{})
	resourceRows                = strings.Join(resourceFieldNames, ",")
	resourceRowsExpectAutoSet   = strings.Join(stringx.Remove(resourceFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	resourceRowsWithPlaceHolder = strings.Join(stringx.Remove(resourceFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheResourceIdPrefix = "cache:resource:id:"
)

type (
	resourceModel interface {
		Insert(ctx context.Context, data *Resource) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Resource, error)
		Update(ctx context.Context, newData *Resource) error
		Delete(ctx context.Context, id int64) error
	}

	defaultResourceModel struct {
		sqlc.CachedConn
		table string
	}

	Resource struct {
		Id          int64          `db:"id"`
		X           sql.NullInt64  `db:"x"`
		Y           sql.NullInt64  `db:"y"`
		Width       sql.NullInt64  `db:"width"`
		Height      sql.NullInt64  `db:"height"`
		Type        sql.NullString `db:"type"`
		Path        sql.NullString `db:"path"`
		Thumbnail   sql.NullString `db:"thumbnail"`
		IsThumbnail int64          `db:"is_thumbnail"`
		Alias       sql.NullString `db:"alias"`
	}
)

func newResourceModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultResourceModel {
	return &defaultResourceModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`resource`",
	}
}

func (m *defaultResourceModel) Delete(ctx context.Context, id int64) error {
	resourceIdKey := fmt.Sprintf("%s%v", cacheResourceIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, resourceIdKey)
	return err
}

func (m *defaultResourceModel) FindOne(ctx context.Context, id int64) (*Resource, error) {
	resourceIdKey := fmt.Sprintf("%s%v", cacheResourceIdPrefix, id)
	var resp Resource
	err := m.QueryRowCtx(ctx, &resp, resourceIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", resourceRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultResourceModel) Insert(ctx context.Context, data *Resource) (sql.Result, error) {
	resourceIdKey := fmt.Sprintf("%s%v", cacheResourceIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, resourceRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.X, data.Y, data.Width, data.Height, data.Type, data.Path, data.Thumbnail, data.IsThumbnail, data.Alias)
	}, resourceIdKey)
	return ret, err
}

func (m *defaultResourceModel) Update(ctx context.Context, data *Resource) error {
	resourceIdKey := fmt.Sprintf("%s%v", cacheResourceIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, resourceRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.X, data.Y, data.Width, data.Height, data.Type, data.Path, data.Thumbnail, data.IsThumbnail, data.Alias, data.Id)
	}, resourceIdKey)
	return err
}

func (m *defaultResourceModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheResourceIdPrefix, primary)
}

func (m *defaultResourceModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", resourceRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultResourceModel) tableName() string {
	return m.table
}
